from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from datetime import datetime
import io

class PDFReportGenerator:
    def __init__(self):
        self.styles = getSampleStyleSheet()
        self.story = []
        
    def generate_diagnosis_report(self, patient_name, diagnosis, confidence, probabilities, radiologist_email, timestamp):
        """Generate a PDF report for a single diagnosis"""
        
        # Create a BytesIO buffer
        pdf_buffer = io.BytesIO()
        
        # Create PDF document
        doc = SimpleDocTemplate(pdf_buffer, pagesize=letter)
        story = []
        
        # Custom styles
        title_style = ParagraphStyle(
            'CustomTitle',
            parent=self.styles['Heading1'],
            fontSize=24,
            textColor=colors.HexColor('#1f77b4'),
            spaceAfter=30,
            alignment=1  # Center
        )
        
        heading_style = ParagraphStyle(
            'CustomHeading',
            parent=self.styles['Heading2'],
            fontSize=14,
            textColor=colors.HexColor('#333333'),
            spaceAfter=12,
            spaceBefore=12
        )
        
        normal_style = self.styles['Normal']
        
        # Title
        story.append(Paragraph("🫁 Clinical Diagnostic Report", title_style))
        story.append(Spacer(1, 0.3*inch))
        
        # Patient Information Section
        story.append(Paragraph("Patient Information", heading_style))
        patient_data = [
            ['Patient ID:', patient_name],
            ['Radiologist:', radiologist_email],
            ['Report Date:', timestamp],
        ]
        patient_table = Table(patient_data, colWidths=[2*inch, 4*inch])
        patient_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (0, -1), colors.HexColor('#f0f0f0')),
            ('TEXTCOLOR', (0, 0), (-1, -1), colors.black),
            ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
            ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, -1), 11),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 12),
            ('GRID', (0, 0), (-1, -1), 1, colors.grey),
        ]))
        story.append(patient_table)
        story.append(Spacer(1, 0.3*inch))
        
        # Diagnosis Section
        story.append(Paragraph("Diagnosis Results", heading_style))
        
        # Map diagnosis to severity color
        severity_colors = {
            'Normal': colors.HexColor('#00D084'),
            'Pneumonia': colors.HexColor('#FFA500'),
            'Tuberculosis': colors.HexColor('#FF0000')
        }
        
        diagnosis_color = severity_colors.get(diagnosis, colors.grey)
        
        diagnosis_data = [
            ['Primary Diagnosis:', diagnosis],
            ['Confidence Score:', f"{confidence:.1f}%"],
        ]
        diagnosis_table = Table(diagnosis_data, colWidths=[2*inch, 4*inch])
        diagnosis_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (0, -1), colors.HexColor('#f0f0f0')),
            ('BACKGROUND', (1, 0), (1, 0), diagnosis_color),
            ('TEXTCOLOR', (1, 0), (1, 0), colors.white),
            ('TEXTCOLOR', (0, 0), (-1, -1), colors.black),
            ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
            ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
            ('FONTNAME', (1, 0), (1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, -1), 11),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 12),
            ('GRID', (0, 0), (-1, -1), 1, colors.grey),
        ]))
        story.append(diagnosis_table)
        story.append(Spacer(1, 0.3*inch))
        
        # Prediction Probabilities Section
        story.append(Paragraph("Prediction Probabilities", heading_style))
        
        prob_data = [['Classification', 'Probability']]
        for class_name, prob in probabilities.items():
            prob_data.append([class_name, f"{prob*100:.2f}%"])
        
        prob_table = Table(prob_data, colWidths=[3*inch, 3*inch])
        prob_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#1f77b4')),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
            ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, -1), 10),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 12),
            ('GRID', (0, 0), (-1, -1), 1, colors.grey),
        ]))
        story.append(prob_table)
        story.append(Spacer(1, 0.5*inch))
        
        # Footer
        story.append(Paragraph("This report was generated by the Clinical Diagnostic System. "
                              "Please consult with a qualified radiologist for final diagnosis.", 
                              self.styles['Normal']))
        
        # Build PDF
        doc.build(story)
        
        # Return the buffer content
        pdf_buffer.seek(0)
        return pdf_buffer.getvalue()
