[supabase]
url = "https://awcrfnlrywbfyvytmasq.supabase.co"
key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF3Y3JmbmxyeXdiZnl2eXRtYXNxIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3NzQ2MDMzNiwiZXhwIjoyMDkzMDM2MzM2fQ.NPditwFc17b6vfSMkml39AQFhl6lv8T6y_hYzAzrcps"